### ISSUE TITLE
Error sqlite3.OperationalError docker-compose-dev.yml

### ISSUE THREAD

**Issue by mindog** [certat/intelmq-docker#20]
after following instruction https://github.com/certat/intelmq-docker/blob/main/DEVELOP-GUIDE.md, dev containers doesn't load.

I got error:
```
intelmq-docker-intelmq-1  | Loading config from /etc/intelmq/api-config.json
intelmq-docker-intelmq-1  | Traceback (most recent call last):
intelmq-docker-intelmq-1  |   File "/usr/local/bin/intelmq-api-adduser", line 4, in <module>
intelmq-docker-intelmq-1  |     __import__('pkg_resources').run_script('intelmq-api==3.0.1', 'intelmq-api-adduser')
intelmq-docker-intelmq-1  |   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 651, in run_script
intelmq-docker-intelmq-1  |     self.require(requires)[0].run_script(script_name, ns)
intelmq-docker-intelmq-1  |   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1448, in run_script
intelmq-docker-intelmq-1  |     exec(code, namespace, namespace)
intelmq-docker-intelmq-1  |   File "/usr/local/lib/python3.9/dist-packages/intelmq_api-3.0.1-py3.9.egg/EGG-INFO/scripts/intelmq-api-adduser", line 27, in <module>
intelmq-docker-intelmq-1  |     session_store = intelmq_api.session.SessionStore(str(api_config.session_store), api_config.session_duration)
intelmq-docker-intelmq-1  |   File "/usr/local/lib/python3.9/dist-packages/intelmq_api-3.0.1-py3.9.egg/intelmq_api/session.py", line 86, in __init__
intelmq-docker-intelmq-1  |     self.init_sqlite_db()
intelmq-docker-intelmq-1  |   File "/usr/local/lib/python3.9/dist-packages/intelmq_api-3.0.1-py3.9.egg/intelmq_api/session.py", line 100, in init_sqlite_db
intelmq-docker-intelmq-1  |     with self.connect() as con:
intelmq-docker-intelmq-1  |   File "/usr/local/lib/python3.9/dist-packages/intelmq_api-3.0.1-py3.9.egg/intelmq_api/session.py", line 91, in connect
intelmq-docker-intelmq-1  |     return sqlite3.connect(self.dbname, check_same_thread=False,
intelmq-docker-intelmq-1  | sqlite3.OperationalError: unable to open database file
intelmq-docker-intelmq-1  | /opt/entrypoint-dev.sh: line 29: cd: /etc/intelmq-api: No such file or directory
```

**Comment by einar-lanfranco** [comment]
Hi Mindog, i just made a new pull request, please let me know if it works with the new version, the main problem it's all /etc/intelmq point to /opt/intelmq and the scripts failed.
